version: '3.9'
services:
  couplestory-web:
    build:
      context: .
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-}
    image: couplestory-web:latest
    container_name: couplestory-web
    restart: unless-stopped
    ports:
      - "8091:8091"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
